[project]
name = "coding-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-ai>=2.18.0",
    "prompt-toolkit>=3.0",
    "python-dotenv>=1.0",
    "rich>=13.0",
    "typer",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
