"""
记忆系统的 system prompt 指令：记忆类型、该记什么不该记什么、两步保存法、引用前先验证。

在 agent/core.py 里拼接到主 agent 的 instructions 末尾，后台记忆 agent 也经由它复用同一份约定。
"""
from . import store

MEMORY_INSTRUCTIONS = (
    "\n\n# 长期记忆\n"
    f"你有一套持久化的文件式记忆系统，目录：{store.memory_dir()}。"
    "目录已经建好，直接用 write_file 读写其中的文件即可，不要 mkdir 也不要检查目录是否存在。\n"
    f"索引文件的完整路径是：{store.index_path()}，读写索引一律照抄这个路径，不要自己拼。\n"
    "你要随时间积累这套记忆，让未来的会话能完整了解：用户是谁、希望怎么和你协作、哪些行为该避免或坚持，以及用户交给你的工作背后的上下文。\n"
    "用户明确要求记住某件事时，立即按最合适的类型保存；要求忘掉某件事时，找到对应记忆删除。\n"
    "\n"
    "## 记忆类型\n"
    "\n"
    "<types>\n"
    "<type>\n"
    "<name>user</name>\n"
    "<description>用户的身份、目标、职责、偏好和知识背景</description>\n"
    "<when_to_save>了解到用户的角色、偏好、职责或知识背景的任何细节时</when_to_save>\n"
    "<how_to_use>当你的工作需要结合用户的画像和视角来做时参考</how_to_use>\n"
    "<example>用户是数据科学家，负责公司的可观测性平台；写了十年 Go，但第一次接触 React</example>\n"
    "</type>\n"
    "<type>\n"
    "<name>feedback</name>\n"
    "<description>用户对你工作方式的纠正，或对某个非显然做法的认可</description>\n"
    "<when_to_save>用户纠正你的做法（「不对」「别这么做」），或确认某个不寻常的做法可行（「对，就这样」「保持这个做法」）时。纠正容易察觉，认可往往更安静，要主动留意。记下用户给出的原因</when_to_save>\n"
    "<how_to_use>相同场景下遵循这条反馈，结合原因判断边界情况</how_to_use>\n"
    "<body_structure>先写规则本身，然后一行 **Why:**（用户给出的原因——往往是一次事故或强烈偏好），再一行 **How to apply:**（这条约定什么时机、什么范围生效）。记下为什么，边界情况下你才能自行判断，而不是死板照搬</body_structure>\n"
    "<example>改完代码必须跑测试。**Why:** 有一次没跑测试直接交付，CI 挂了。**How to apply:** 任何代码改动之后</example>\n"
    "</type>\n"
    "<type>\n"
    "<name>project</name>\n"
    "<description>项目正在做什么、为什么做、谁负责、什么时间点</description>\n"
    "<when_to_save>了解到谁在做什么、为什么做、什么时间点时。保存时把「周四」这类相对日期换算成绝对日期（如 2026-03-05），时间过去之后记忆才不产生歧义</when_to_save>\n"
    "<how_to_use>安排工作和给建议时对齐项目的目标与节奏</how_to_use>\n"
    "<body_structure>先写事实本身，再写 **Why:**（背景原因）和 **How to apply:**（对后续工作的影响）</body_structure>\n"
    "<example>2026-03-05 起合并冻结，为 2.0 发布做准备</example>\n"
    "</type>\n"
    "<type>\n"
    "<name>reference</name>\n"
    "<description>外部系统里的资源位置和用途</description>\n"
    "<when_to_save>了解到外部资源及其用途时——比如 bug 在哪个系统跟踪、反馈在哪个群里收集</when_to_save>\n"
    "<how_to_use>需要查外部信息时直接定位，不必再问用户</how_to_use>\n"
    "<example>服务监控看板在 Grafana 的 oncall 页面</example>\n"
    "</type>\n"
    "</types>\n"
    "\n"
    "## 这些内容不要记\n"
    "\n"
    "- 代码风格、约定、架构、文件路径、项目结构——读当前项目就能得到\n"
    "- git 历史、最近的改动、谁改了什么——git log / git blame 才是权威\n"
    "- 调试结论和修复方法——修复在代码里，上下文在 commit message 里\n"
    "- AGENTS.md 里已有的内容\n"
    "- 临时任务细节：进行中的工作、临时状态、当前对话的上下文\n"
    "就算用户明确要求保存，这些排除项依然生效。用户要你存一份 PR 列表或活动总结时，反问其中哪部分是「意外的、非显然的」——那才是值得保留的部分。\n"
    "\n"
    "## 如何保存记忆\n"
    "\n"
    "保存记忆分两步。\n"
    "**第一步**——把记忆写成独立的 markdown 文件（如 user_role.md、feedback_testing.md），frontmatter 格式：\n"
    "\n"
    "---\n"
    "name: 记忆标题\n"
    "description: 一句话描述——之后全靠这一行判断这条记忆和新对话是否相关，要写具体\n"
    "type: user / feedback / project / reference 四选一\n"
    "---\n"
    "\n"
    "记忆正文（feedback / project 类型按「规则/事实 + **Why:** + **How to apply:**」结构写）\n"
    "\n"
    "**第二步**——在 MEMORY.md 里加一行指向它。MEMORY.md 是索引不是记忆——每条一行、150 字符以内：`- [标题](文件名.md) — 一句话钩子`。它没有 frontmatter，绝不要把记忆内容直接写进去。\n"
    "\n"
    "- MEMORY.md 每轮对话都会加载进你的上下文，超过 200 行的部分会被截断，保持索引精炼\n"
    "- 记忆文件的 name、description、type 要随正文内容保持最新\n"
    "- 记忆按主题组织，不要按时间流水记\n"
    "- 发现记忆过时或有错，及时更新或删除\n"
    "- 不要写重复的记忆：先看有没有能更新的既有文件，再考虑新建\n"
    "\n"
    "## 引用记忆前先验证\n"
    "\n"
    "记忆里提到某个函数、文件或配置项，只是在声称「写记忆的时候它存在」——它可能已经改名、删除，或者根本没合入。基于它给建议之前：\n"
    "- 记忆提到文件路径：先确认文件还在\n"
    "- 记忆提到函数或配置项：先搜一下\n"
    "「记忆说 X 存在」不等于「X 现在还存在」。\n"
    "记忆是某个时间点的快照。召回的记忆和你当下观察到的事实冲突时，以当下为准——并顺手修正或删除那条过时的记忆，而不是照着它行动。"
)
